os: linux
dist: trusty
sudo: false
language: python

python:
  - 3.6
  - 2.7
  - 3.3
  - 3.5
  - 3.4

addons:
  apt:
    packages:
      - libluajit-5.1-dev
      - liblua5.2-dev

env:
  global:
    - CFLAGS="$CFLAGS -g -flto"
    - LDFLAGS="$LDFLAGS -flto"
  matrix:
    - LUA=luajit-5.1
    - LUA=lua5.2
    - LUA=bundle

matrix:
  include:
    - python: 3.7
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=luajit-5.1
    - python: 3.7
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=lua5.2
    - python: 3.7
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=bundle
    - python: 3.8-dev
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=luajit-5.1
    - python: 3.8-dev
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=lua5.2
    - python: 3.8-dev
      dist: xenial    # Required for Python 3.7
      sudo: required  # travis-ci/travis-ci#9069
      env: LUA=bundle
    - python: pypy
      env: LUA=luajit-5.1
    - python: pypy
      env: LUA=lua5.2
    - python: pypy
      env: LUA=bundle
    - python: pypy3
      env: LUA=luajit-5.1
    - python: pypy3
      env: LUA=lua5.2
    - python: pypy3
      env: LUA=bundle

cache: pip

# requirements.txt are automatically installed during 'install' phase.

before_script:
  - pip install -U tox-travis virtualenv
  - if [[ "$LUA" == "lua5.2" ]]; then export SETUP_OPTIONS="--no-luajit" ; fi
  - if [[ "$LUA" == "bundle" ]]; then export SETUP_OPTIONS="--use-bundle" ; fi

script: tox
