version: 1.0.{build}

environment:
  matrix:
  - python: 27
  - python: 27-x64
  - python: 34
  - python: 34-x64
  - python: 35
  - python: 35-x64
  - python: 36
  - python: 36-x64
  - python: 37
  - python: 37-x64

install:
  - SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%
  - python -m pip.__main__ install -U pip wheel setuptools

build: off
build_script:
  - pip install -U tox-travis virtualenv
  - tox

test: off

artifacts:
  - path: dist/*.whl
    name: wheels
